### ISSUE TITLE
TypeScript failure

### ISSUE THREAD

**Issue by delvedor** [nodejs/undici#1223]
The [last release](https://github.com/nodejs/undici/releases/tag/v4.14.0) introduced a TypeScript bug that does not allow TypeScript to compile. It looks like the bug has been introduced in https://github.com/nodejs/undici/pull/1200.

Error:
```
node_modules/undici/types/mock-interceptor.d.ts:74:14 - error TS2304: Cannot find name 'Headers'.

74     headers: Headers;
                ~~~~~~~
```

To reproduce, create a empty project, install `undici`, `typescript` and `@types/node` and try to compile the following:
```ts
import { Request } from 'undici'
```

I don't know how to fix it, if anyone has an idea I can open a pr.

**Comment by delvedor** [comment]
It looks like this can be solved by adding  `"dom"` to the project `tsconfig.json`.
```diff
    "lib": [
      "esnext",
+      "dom"
    ]
```

Is there any other way to solve this?

**Comment by ronag** [comment]
Missing an import for Headers?
